#ifndef certs_h
#define certs_h

// Amazon's root CA. This should be the same for everyone.
const char AWS_CERT_CA[] = "-----BEGIN CERTIFICATE-----\n" 
                    "MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\n"
                    "ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\n"
                    "b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL\n"
                    "MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv\n"
                    "b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj\n"
                    "ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM\n"
                    "9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw\n"
                    "IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6\n"
                    "VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L\n"
                    "93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm\n"
                    "jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\n"
                    "AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA\n"
                    "A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI\n"
                    "U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs\n"
                    "N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv\n"
                    "o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU\n"
                    "5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy\n"
                    "rqXRfboQnoZsG4q5WTP468SQvvG5\n"
                     "-----END CERTIFICATE-----\n";

// The private key for your device
const char AWS_CERT_PRIVATE[] =  "-----BEGIN RSA PRIVATE KEY-----\n" 
                        "MIIEowIBAAKCAQEAwH0e/0mIhPEzvpnfApsXvTE92O1D5zD3xftej8vzE+fD4H/t\n"
                        "ce2q4/YJ5JnQkysXyVVrjLwyaqoA9vsJbFabtUoGoXDSARPTmk0dOAxcJCIPMAkD\n"
                        "RRG3u7xrVw2IjtmTWjizXI2qSeJb+XCMw7QoQMBCEacT0roD+Qk6Iu5fmjM4T7Ns\n"
                        "sPlWTwuxIGgvpv6UNzLWf7P9w7bZBEADUEjWuHZ/yntP97pHhx4ru7WQSche2YLo\n"
                        "H4Q5adqv0w2QMQwzhkhlacGG8uCUMfu5AE9kTP0YtA34qKCj297LCgl8I8YRaD0y\n"
                        "2szwn69V+V2Kh5DPayk600oX3myvkfbv/+eY9wIDAQABAoIBAHrV3dgPtt0Ph3PU\n"
                        "gaoKCwYizFMIZlK8vwFKvjeJcR98wVUcjgwsHOfIdNu7BI1F7LIAntd6qbnDr0Xt\n"
                        "QUAvrMHt8XlIo9soKdrH5yODT7GHQqXmun1zJwrY3K765fAzDIOAt4USql7n4sW1\n"
                        "ez7QUvevOPpG4rGRH0PnDYCJGd0uQpdGEekGPdJl6ikEKOvVcvFqgfRzHsI5vLjv\n"
                        "UQN7i5ZnWuf4ITQLP3okmwr5/6DH47tNf9dNURI1hdVAzXrZ32kSgenIOC2eY8Bv\n"
                        "BYBN+x+UkbMn509decmw46Rxkeg22szO+4qO3e811CwWvAfPtJ1Ohdjif1iFgGI3\n"
                        "fwQsrrECgYEA7ITzINJp5akc9fpC5+L040cDHawiM6lciF1ixmrUrDKm9WTA+8Mw\n"
                        "mtG9v2ZopV8h6nspo7D6olJapOMa+pxSZVtHgYFf7DT1I8GVgBG/QdKSQuER3si6\n"
                        "/N9oa1+AXon4yv3ftQAhhfprkEYZjDt4GQxSN1q6Au8sbnMu7FiqmYUCgYEA0FfH\n"
                        "c24TmnbTV2rDGNQfPsXeMRPJTRmm5b9WIaoWT0MoU5Fm+ctZQlBaKPpxiweYF1Tg\n"
                        "uNboozoUyYJmKPHCbCAYld+He4l+kl6uDHjFLA3taqsgRj7RzOTE7999F2tylvXF\n"
                        "McuSgBf9RbT2NGSVNu78mlAM/TolAnQM0i8U00sCgYA6AMC/I9rkf3yitiUCSR5V\n"
                        "Pmz9MeGRWc9fgcdfcYOGV0WqmHLbSxr4XMdz0OGI7LOclWe4xQYyGJAyL5/GJd/v\n"
                        "C1uV3uxvOO2FP0wyhCerNMC5tghz4jY5HXC2JE2O4bcp0OizsryF5svKLebGBS+G\n"
                        "tQbUnGNRpOX4kDbJr1TnIQKBgEZ8LAIlT4SGhuGgQPj5asi18IHyC7yF3S0FGoKx\n"
                        "JHMUaWQ8YPZJkZ0Zyibq89bxbscV9CEUtAfk8ntqHl3jzL7/7NFnmlJ1JdknJwMZ\n"
                        "KLvKynO4CWc6gYgsLWRp28w8kbv40goSsTGc7BbVLiZzkPfQyqz6QCq7rSGzWVMS\n"
                        "kp0ZAoGBAMvNQxj55rf2vO6ZwYWOqmpTuqL36OatazkDtzJfO12mCrmD93bOCTRn\n"
                        "4q+1syoIodxkvCa/3RYb13xvjYN46byWXAquGgvH0pjOQU4gVt1HjN9Bo4z8NQYQ\n"
                        "sZX/a4O1AQrUFFHjrOMrfXHt/P9pRtyQf7zQngbr8P+zlJC5YrEu\n"
                         "-----END RSA PRIVATE KEY-----\n";

// The certificate for your device
const char AWS_CERT_CRT[] = "-----BEGIN CERTIFICATE-----\n" 
                          "MIIDWTCCAkGgAwIBAgIUOVEspxNqQtraIFEtTFIh2ANMjUIwDQYJKoZIhvcNAQEL\n"
                          "BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g\n"
                          "SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIwMDYyNTEzMTIw\n"
                          "M1oXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0\n"
                          "ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMB9Hv9JiITxM76Z3wKb\n"
                          "F70xPdjtQ+cw98X7Xo/L8xPnw+B/7XHtquP2CeSZ0JMrF8lVa4y8MmqqAPb7CWxW\n"
                          "m7VKBqFw0gET05pNHTgMXCQiDzAJA0URt7u8a1cNiI7Zk1o4s1yNqkniW/lwjMO0\n"
                          "KEDAQhGnE9K6A/kJOiLuX5ozOE+zbLD5Vk8LsSBoL6b+lDcy1n+z/cO22QRAA1BI\n"
                          "1rh2f8p7T/e6R4ceK7u1kEnIXtmC6B+EOWnar9MNkDEMM4ZIZWnBhvLglDH7uQBP\n"
                          "ZEz9GLQN+Kigo9veywoJfCPGEWg9MtrM8J+vVfldioeQz2spOtNKF95sr5H27//n\n"
                          "mPcCAwEAAaNgMF4wHwYDVR0jBBgwFoAUr99IC1ZCWi3r4pkDetDoiyazAMkwHQYD\n"
                          "VR0OBBYEFEBzXv3CzAVCWCM8dHIF/NYNbs+TMAwGA1UdEwEB/wQCMAAwDgYDVR0P\n"
                          "AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQCsneesXcd6RMmmRkYTg04SYZjg\n"
                          "08a4+vtmdOx9OnPinIvxJqX1O1FeEk1ao5Mir1sp0Rxd5QOdccMA0mQp79kbFYjF\n"
                          "wwhonfYqfMBYrS9GNCojtoGo1j7AIPL3KFUG87yolu3rBm3tT+rz3adIeynOPJHF\n"
                          "qIa6tsRa7m2JzN5Y2iDNe0dGeRjaj8N+66TpLfNtf2WNW6IhcbHKFrgRzvfZc3a6\n"
                          "PIljzWpJutftnD0fnQml84dfMGl1NfGEju4id5A2v5JKuexs20VfOVHCIYUltvJ8\n"
                          "e3MTNHWnR1ZWFyDLlUXZHE009Dx+v8TJJdKycpoo+jeHPr/MmREPy3sSrC5U\n"
                          "-----END CERTIFICATE-----\n";

#endif
